---
apiVersion: v1
kind: ConfigMap
metadata:
 name: collector-config
 namespace: beyla
data:
 collector.yaml: |
   receivers:
     otlp:
       protocols:
         grpc:
           endpoint: ${env:MY_POD_IP}:4317
         http:
           endpoint: ${env:MY_POD_IP}:4318
   processors:
     batch:
     memory_limiter:
       # 80% of maximum memory up to 2G
       limit_mib: 1500
       # 25% of limit up to 2G
       spike_limit_mib: 512
       check_interval: 5s
   extensions:
     zpages: {}
   exporters:
     # logging:
     otlp:
       endpoint: "tempo-distributor.tempo-test:4317"
       insecure: true
   service:
     extensions: [zpages]
     pipelines:
       traces/1:
         receivers: [otlp]
         processors: [memory_limiter, batch]
         exporters: [otlp]
       # metrics:
       #   receivers: [otlp]
       #   processors: [batch]
       #   exporters: [logging]
