apiVersion: v1
kind: ServiceAccount
metadata:
 name: beyla
 namespace: beyla
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
 name: beyla
rules:
 - apiGroups: [ "apps" ]
   resources: [ "replicasets" ]
   verbs: [ "list", "watch" ]
 - apiGroups: [ "" ]
   resources: [ "pods", "services", "nodes" ]
   verbs: [ "list", "watch" ]
 - apiGroups: [""]
   resources: ["pods", "nodes"]
   verbs: ["get", "list", "watch"]
 - apiGroups: ["apps"]
   resources: ["deployments"]
   verbs: ["get", "list", "watch"]
 - apiGroups: ["monitoring.coreos.com"]
   resources: ["servicemonitors"]
   verbs: ["get", "list", "watch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 name: beyla
subjects:
 - kind: ServiceAccount
   name: beyla
   namespace: beyla
roleRef:
 kind: ClusterRole
 name: beyla
 apiGroup: rbac.authorization.k8s.io
